 name: cd

 on:
   push:
     branches:
       - master

 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: build-and-push
       env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       run: |
         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
         docker build ./ -t sason/feel-covid-moh-data-collector:latest
         docker push sason/feel-covid-moh-data-collector:latest